# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the application will run
ENV PORT=5001
EXPOSE $PORT

# Set environment variables
ENV CLOUDINARY_NAME diuh7ykom
ENV CLOUDINARY_API_KEY 589598586315694
ENV CLOUDINARY_API_SECRET usW9W7LD8I1-GnALVj41B_VZIMA
ENV MONGO_URI mongodb+srv://ctse:lollal12345@ctse.ztoiwyn.mongodb.net/?retryWrites=true&w=majority&appName=CTSE
ENV SECRET nhnhnskfalhfksahkhffalfaalf

# Command to run the application
CMD ["npm", "start"]
