name: Build and Push to Docker Hub

on:
  push:
    branches: [ Dev-Nadun ]  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build Docker image for Inventory Service
      run: |
       docker build -t ecommercemicroservice/inventoryservice:latest ./backend/InventoryService

    - name: Push Docker image for Inventory Service
      run: |
        docker push ecommercemicroservice/inventoryservice:latest 

    - name: Build Docker image for Product Service
      run: |
        docker build -t ecommercemicroservice/productservice:latest ./backend/ProductService  

    - name: Push Docker image for Product Service
      run: |
        docker push ecommercemicroservice/productservice:latest  
