name: Snyk Security Scan

on:
  push:
    branches: [ Dev-Nadun ]

jobs:
  snyk-inventory:
    name: Snyk - Inventory Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Inventory)
        run: |
          cd backend/inventoryService
          npm install

      - name: Run Snyk for Inventory Service
        run: |
          cd backend/inventoryService
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-product:
    name: Snyk - Product Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Product)
        run: |
          cd backend/productService
          npm install

      - name: Run Snyk for Product Service
        run: |
          cd backend/productService
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
