name: Snyk Security Scan

on:
  push:
    branches: [ Dev-Nadun ]

jobs:
  snyk-inventory:
    name: Snyk - Inventory Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to inventoryService and install dependencies
        working-directory: backend/inventoryService
        run: npm install

      - name: Run Snyk for Inventory Service
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: backend/inventoryService

  snyk-product:
    name: Snyk - Product Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to productService and install dependencies
        working-directory: backend/productService
        run: npm install

      - name: Run Snyk for Product Service
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: backend/productService
