name: Snyk Security Scan

on:
  push:
    branches: [ Dev-Nadun ]

jobs:
  snyk-inventory:
    name: Snyk - Inventory Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend/InventoryService
          npm install

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd backend/InventoryService
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

          
  snyk-product:
    name: Snyk - Product Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/ProductService

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test